import "./globals.css";
import Footer from "@/component/Footer";
import Navbar from "@/component/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html theme="dark" lang="en">
      <body className="bg-slate-600 font-serif ">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
